### ISSUE TITLE
I can not convert from xml to txt

### ISSUE THREAD

**Issue by agar3s** [cstubben/pmcXML#2]
I'm trying to retrieve a pmc xml document and convert it to a txt, 6 months ago it was working good, but now the documents contains new headers information (xmlns="http://www.openarchives.org/OAI/2.0/"), when I try to convert the document to txt I have the following error:

``` R
    doc= pmcOAI( 'PMC4515827' )
    txt <- pmcText(doc, sentence=FALSE)
```

```
NOTE: No sections found, using Main
Warning messages:
1: In xpathApply.XMLInternalDocument(doc, path, fun, ..., namespaces = namespaces,  :  the XPath query has no namespace, but the target document has a default namespace. This is often an error and may explain why you obtained no results
```

**Comment by cstubben** [comment]
I wrote most of the xpath using XML docs from NCBI Entrez and their XML does not have a namespace.  When I switched to OAI,  I just removed the xmlns attributes so I could keep the same xpath.  This doc has a \txmlns and the `gsub` in `pmcOAI` below missed it, so I removed the space before the xmlns and uploaded a new version (which may cause problems with other ids?) 

``` R
#   x[1] <- gsub(" xmlns=[^ ]*" , "", x[1])
# see PMC4515827 with tab before xmlns,  \txmlns=
   x[1] <- gsub("xmlns=[^ ]*" , "", x[1])
```

**Comment by agar3s** [comment]
It works very good right now, thank you so much.
You made a great job here :+1:
